version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

#  jupyter:
#    image: jupyter/base-notebook:python-3.9
#    container_name: jupyter-notebook
#    depends_on:
#      - kafka
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./notebooks:/home/jovyan/work
#      - ./data:/home/jovyan/data
#      - ./requirements.txt:/tmp/requirements.txt
#    environment:
#      JUPYTER_ENABLE_LAB: "yes"
#      JUPYTER_TOKEN: ""
#    user: root  # Run as root user to resolve permission issues
#    command: >
#      bash -c "apt-get update &&
#               apt-get install -y openjdk-11-jdk &&
#               pip install --no-cache-dir -r /tmp/requirements.txt &&
#               jupyter lab --ip=0.0.0.0 --allow-root"

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-notebook
    depends_on:
      - kafka
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./custom:/home/jovyan/.jupyter/custom
    environment:
      JUPYTER_TOKEN: ""
    command: >
      jupyter lab --ip=0.0.0.0 --allow-root

  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./kafka_producer.py:/app/kafka_producer.py  # Mount the file if not copying
      - ./requirements.txt:/app/requirements.txt  # Mount the requirements file
      - ./data:/app/data
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 1
