version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./jupyter/notebooks:/home/jovyan/notebooks

  kafka-producer:
    build:
      context: ./kafka-producer  # Ensure the context points to the kafka-producer folder
      dockerfile: Dockerfile.kafka_producer
    container_name: kafka-producer
    volumes:
      - ./kafka-producer/scripts:/app/scripts
      - ./data:/app/data
    environment:
      PYTHONUNBUFFERED: 1

  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile.flask
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./flask/templates:/app/templates
      - ./flask/flask_app.py:/app/flask_app.py



