FROM python:3.9-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY flask_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Flask app and templates
COPY flask_app/ /app/

EXPOSE 5000

CMD ["python", "flask_app.py"]
