FROM python:3.9-slim

WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Flask app files and templates
COPY flask/flask_app.py .
COPY flask/templates/ ./templates/

EXPOSE 5000

CMD ["python", "flask_app.py"]
